# Generated by Django 5.0 on 2024-01-13 08:14

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("insta_bot", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="account_details",
            name="password",
            field=models.CharField(max_length=400),
        ),
    ]
